name: Daily Report

on:
  schedule:
    # 00:10 Asia/Manila = 16:10 UTC (previous day)
    - cron: "10 16 * * *"
  workflow_dispatch:
    inputs:
      no_send:
        description: "Don't send emails (test run only)"
        required: false
        type: boolean
        default: true
      custom_date:
        description: "Custom date for report (e.g., 'Sep 9', 'September 9, 2024', '2024-09-09')"
        required: false
        default: ""
      mock_receiver_email:
        description: "Override recipient for this run (optional)"
        required: false
        default: ""

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      # File path where we will write the service account JSON
      GOOGLE_SERVICE_ACCOUNT_JSON: jogaliga-service-account.json
      # Secrets
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      # Repository variables (configure in Settings > Secrets and variables > Actions > Variables)
      FRONTEND_REPO: ${{ vars.FRONTEND_REPO }}
      BACKEND_REPO: ${{ vars.BACKEND_REPO }}
      DEV1_NAME_FRONTEND: ${{ vars.DEV1_NAME_FRONTEND }}
      DEV2_NAME_FRONTEND: ${{ vars.DEV2_NAME_FRONTEND }}
      DEV1_NAME_BACKEND: ${{ vars.DEV1_NAME_BACKEND }}
      DEV2_NAME_BACKEND: ${{ vars.DEV2_NAME_BACKEND }}
      DEV1_GH_FRONTEND: ${{ vars.DEV1_GH_FRONTEND }}
      DEV2_GH_FRONTEND: ${{ vars.DEV2_GH_FRONTEND }}
      DEV1_GH_BACKEND: ${{ vars.DEV1_GH_BACKEND }}
      DEV2_GH_BACKEND: ${{ vars.DEV2_GH_BACKEND }}
      SHEET_ID: ${{ vars.SHEET_ID }}
      # Toggle sheets/GH behavior
      NO_SHEETS: "False"
      # For manual runs: default to no send (can be overridden)
      # For scheduled runs: always send emails
      NO_SEND: ${{ github.event_name == 'schedule' && 'false' || (github.event.inputs.no_send || 'true') }}
      # Disable mock mode for scheduled runs to ensure real emails are sent
      MOCK_MODE: "False"
      CUSTOM_DATE: ${{ github.event.inputs.custom_date }}
      MANUAL_MOCK: ${{ github.event.inputs.mock_receiver_email != '' && 'True' || 'False' }}
      MOCK_RECEIVER_EMAIL: ${{ github.event.inputs.mock_receiver_email }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread google-auth google-auth-oauthlib yagmail python-dotenv pytest pytest-xdist

      - name: Write Google service account JSON
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > "${GOOGLE_SERVICE_ACCOUNT_JSON}"
          echo "JSON file written, validating..."
          python -c "import json; json.load(open('${GOOGLE_SERVICE_ACCOUNT_JSON}')); print('JSON is valid')"
        shell: bash

      - name: Run tests
        run: |
          pytest -n auto -q

      - name: Run daily report script
        run: |
          python jogaliga_daily_report_mailer.py
