name: Daily Report

on:
  schedule:
    # 23:59 Asia/Manila = 15:59 UTC
    - cron: '59 15 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread google-auth yagmail python-dotenv pytest pytest-xdist

      - name: Write Google service account JSON
        if: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON != '' }}
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > jogaliga-service-account.json
        shell: bash

      - name: Run tests
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: jogaliga-service-account.json
        run: |
          pytest -n auto -q

      - name: Dry-run render (HTML output)
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: jogaliga-service-account.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: |
          python - <<'PY'
from jogaliga_daily_report_mailer import render_daily_report_dry_run
html = render_daily_report_dry_run()
print(html)
PY


